name: First Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
